# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    # Diretório onde vai ser feito o job
    defaults:
      run:
        working-directory: recursividade

    steps:
    - uses: actions/checkout@v2
    - name: Configurando o Java 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compilando o Projeto
      run: mvn compile
    - name: Rodar o Projeto entregando resultado
      run: mvn exec:java
